name: CI
on:
  push:
    branches: [main, staging]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core-bundle-and-installer:
    uses: ./.github/workflows/validate.yml
  app:
    uses: ./.github/workflows/app.yml
