name: CI
on:
  push:
    branches: [main, staging]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core-and-distribution:
    uses: ./.github/workflows/validate.yml
  ui:
    uses: ./.github/workflows/ui-host.yml
